---
ID: "c877c544-695c-41b5-949a-917c288ee381"
Parent: "e30b8a6a-abb6-4d11-93e4-a5b7d7352b28"
Template: "e30b8a6a-abb6-4d11-93e4-a5b7d7352b28"
Path: /sitecore/templates/Project/Common/Content Types/Recommended Pages/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181128T121056Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
